### ISSUE TITLE
What is the difference between the .MSI and .MSP format?

### ISSUE THREAD

**Issue by alanccw** [ironfede/openmcdf#131]
Hi,

What is the difference between the .MSI(MS Installation) and .MSP(MS Installation Patch) file?

I check with this post: https://github.com/ironfede/openmcdf/issues/11#issuecomment-327464559

And find both file types will return "TITLE" property as "Installation Database", no difference.

**Comment by ironfede** [comment]
I don't know internal specs of the 2 formats. MSI should be a full installer package while MSP should be a "patch" package bearing only differences between original and patched files in order to reduce size of package data.
I'm sorry to be late with response and not being more precise.
Best Regards,
Federico
