### ISSUE TITLE
Add Source/PDB nuget package

### ISSUE THREAD

**Issue by ironfede** [ironfede/openmcdf#24]

**Comment by michaelp** [comment]
ETA Monday July 23th

**Comment by michaelp** [comment]
@ironfede 
1. The task is done, please code review and merge.
2.  For the next story, please read the following:  [Strong Name Signing](https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md)
**This is a breaking change**, but it is a required change since to the best of my knowlege it is impossible to strong name sign assemblies on linux, I.e. people will not be able to build the code on linux (debugging is possible due to the issue #24 )
