### ISSUE TITLE
Reading a stream with an initial offset throws System.ArgumentException

### ISSUE THREAD

**Issue by conormcg94** [ironfede/openmcdf#253]
Trying to read a stream with an initial offset throws an ArgumentException in v3.0.0-preview.2. This passes in V2.4
```
    [TestMethod]
    [DataRow("TestStream_v4_512.cfs")]
    public void ReadStreamWithOffset(string fileName)
    {
        using var rootStorage = RootStorage.OpenRead(fileName);
        CfbStream stream = rootStorage.OpenStream("TestStream");

        byte[] buffer = new byte[4];
        stream.Read(buffer, 2, buffer.Length);
      }
```
Exception in FatStream.cs: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection

**Comment by Numpsy** [comment]
Is that trying to read 4 bytes into a 4byte buffer starting at the 3rd byte? (the docs for Stream.Read says it throws when 'The sum of offset and count is larger than the buffer length.')

**Comment by conormcg94** [comment]
Hi Numpsy, yes you are correct. I missed the change in behaviour, in V2.4 the position refers to the index in the stream

V2.4
`int Read(byte[] buffer, long position, int count)`

V3.0
`int Read(byte[] buffer, int offset, int count)`

**Comment by jeremy-visionaid** [comment]
Oh, yup, that's somewhat unfortunate (I think I only ever used the decorator briefly before starting on the rewrite so I never even called it directly myself). It might catch out a few folk who are uprading to the v3 API. I don't think there's much that can be done about it though. Dotnet guidelines are that types post-fixed with "Stream" should implement "Stream" and v3 adheres to that while v2 does not... I'm not sure there is anything left to do but close the issue...
