### ISSUE TITLE
[memory management] investigate possible usage of System.IO.Pipelines in openMCDF API

### ISSUE THREAD

**Issue by michaelp** [ironfede/openmcdf#26]
The following is a list of relevant resources, that IMO applicable to the current situation

1. [System.IO.Pipelines: High performance IO in .NET](https://blogs.msdn.microsoft.com/dotnet/2018/07/09/system-io-pipelines-high-performance-io-in-net/)
1. Also [Span](https://msdn.microsoft.com/en-us/magazine/mt814808)
1. and obviously [post1] (https://blog.marcgravell.com/2018/07/pipe-dreams-part-1.html)
1. [post2] (https://blog.marcgravell.com/2018/07/pipe-dreams-part-2.html)

**Comment by jeremy-visionaid** [comment]
@michaelp I'm too not sure about how applicable Pipelines would be to CFB, since it's more random access data than it is streaming... As part of v3 in #194 I've rewritten things to be mostly based around enumerators with some caching, and added support for reading/writing Spans. It reduce the memory usage to just a few KB and mostly obtains better performance than the native COM based implementation.

**Comment by jeremy-visionaid** [comment]
I'm hopeful that 3.0.0-preview1 should get released to NuGet in the next few days. @ironfede has kindly granted me write access to the repo, so I'll go ahead and close this one as fixed by #194.
