### ISSUE TITLE
Handle range lock sector

### ISSUE THREAD

**Issue by jeremy-visionaid** [ironfede/openmcdf#269]
V4 is supposed to have a range lock sector at 0x7FFFFF00-0x7FFFFFFF to support transactions/concurrency, but there is little detail in MS-CFB on how to handle it:

https://learn.microsoft.com/en-us/openspecs/windows_protocols/ms-cfb/947df128-1f4a-4c02-b6ed-6d1d0c04c02f

**Comment by jeremy-visionaid** [comment]
@ironfede I need to fix up writing ENDOFCHAIN/FREESECT as appropriate in the draft still, but it looks to me like DoCheckSizeLimitReached is incorrect in v2.4 since it compares 0x7FFFFF00 to the sector count (not the stream/file offset)? Not sure if you want to do anything about that...?

**Comment by ironfede** [comment]
@jeremy-visionaid thank you for the point but I have not fully understand what you ask me. Do you want me to fix in 2.4 branch this possible issue? Or do you prefer to chek this issue directly also in 2.4? I will take a look but I'm honestly too much busy at the moment. I will surely take in account your report since I think you're absolutely right in pointing at it in 2.4 but I have to postpone it. Thank you for all of your work!

**Comment by jeremy-visionaid** [comment]
@ironfede Yeah, I'll handle the 3.0 range lock sector if you can fix it for 2.4 if/when you find the time (since you're more familiar with it than me). It's summer over here, so I'm looking to take some much needed time off soon! I'd fix it for 2.4 if I had the time, but just letting you know about it...
