### ISSUE TITLE
Create Compound File from File

### ISSUE THREAD

**Issue by 6Hat** [ironfede/openmcdf#48]
Sorry as I am new to compound files. I need to take a standard image in various formats... whether .jpg or .png etc and convert them to a compound file for an MS Access Bound Object Frame. I am stuck on how you take the physical image file and convert it into a MCDF however? I can find no examples.

I've tried to add the file in as a stream but this is obviously wrong:
`            CompoundFile cf = new CompoundFile();
            CFStream myStream = cf.RootStorage.AddStream(path);`

What I need to get overall is the Binary Value of the compound file with the image stream within it. Any help would be greatly appreciated!

**Comment by ironfede** [comment]
I'm not an expert in the file format your'referencing to but if you want to store an image in a compound file you should read it in a byte array/stream for example with

`byte[] b = File.ReadAllBytes(file);`

and then put it into a stream

```
CompoundFile cf = new CompoundFile(); 
CFStream myStream = cf.RootStorage.AddStream("ImageStream");
myStream.SetData(b);
cf.Save("MyFile.dat");
```

Having said that, I suggest to find an example and some documentation of the relationship between MS Access Bound Object Frame and Compound files because I hvent' found one in a quick search (I may be wrong).

Best Regards,
Federico
