### ISSUE TITLE
Reading 1Table stream in the following file causes ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by hughbe** [ironfede/openmcdf#76]
![image](https://user-images.githubusercontent.com/1275900/100231511-076ce200-2f1f-11eb-84ab-d457cc335e75.png)

[mime001.doc.zip](https://github.com/ironfede/openmcdf/files/5596813/mime001.doc.zip)

**Comment by Sonic-The-Hedgehog-LNK1123** [comment]
I don't know if you have realized this, but the file you provided is **badly corrupted.**

From the programs I tried, the sample application for OpenMCDF was in fact able to read more data from the file than other programs:
* 7-zip wasn't able to open the file at all.
* MiTeC's Structured Storage Viewer couldn't find any streams within the file.
* Microsoft Word 2010 reported the file was corrupted and couldn't open it at all.

Word's "Open and Repair" command was unable to repair the file and reported the same error than opening it normally.

**Comment by hughbe** [comment]
Yup I am aware! Its just that we shouldn't throw in block copy, but rather validate the file

**Comment by ironfede** [comment]
Hi @hughbe , as stated in #75  there's a NoValidation option that allows to be set in order to "try" to get data from corrupted files. If it's blanked out, OpenMcdf should throw a `CFCorruptedFileException` in order to stop before operating on data.
Thank you and sorry for delayed responses,
Best Regards
Federico
