### ISSUE TITLE
Some file's name is missing

### ISSUE THREAD

**Issue by anemos78** [ironfede/openmcdf#9]
Hi Federico.

I am using the latest version.But Some file's name is missing. 

On 2.0:
For example: **[1]CompObj** Only show charcode **1** and **CompObj**
For example: **[3]VBFrame** Only show charcode **3** and **VBFrame**

On 2.1:
For example: **[1]CompObj** Only show [] and CompObj
For example: **[3]VBFrame** Only show [] and VBFrame

File name must be **[1]CompObj**
but dont show/get file name
**Note : It is a Excel (xls) file!**

Screenshots are attached.

Thanks in advance

![resim](https://user-images.githubusercontent.com/30706420/28947261-9d956c9c-78b7-11e7-95a4-688a0dd510e6.png)

![resim](https://user-images.githubusercontent.com/30706420/28947272-aa331b0c-78b7-11e7-9c6c-4a97137f38bb.png)

**Comment by ironfede** [comment]
Anemos, I'm taking a look at OpenMcdf behaviour for issue you opened.
Openmcdf doesn't  show the string "[5]" or "[1]" because imho that could be a misleading information.

Unicode character \u0005 is shown by 7zip in a way that make it recognizable at a first gance but this character is the control character ENQuiry (ALT+05) and it is not actually printable (this is why a placeholder character is shown in Structured Storage eXplorer).  
If you use OpendMcdf API, you CAN use character value even if it is not printable.

Finally, I can show you why this 7zip choice can be misleading:
What if we have two streams, one with the non-printable character that is "interpreted" as "[5]" and one with 3 printable characters "[5]" in the same position?

![image](https://user-images.githubusercontent.com/18366648/28995962-d8a6d6f0-79f6-11e7-945e-8db10c225b42.png)

Thank You for your report, it gave me the occasion to explain this design choice.
Best Regards,
Federico

**Comment by anemos78** [comment]
You were right. When all binary stream of xls file without the square brackets I saved "xls" with explorer, file is opened succesfully. "[5]" or "[3]" added extra by 7-zip and unnecessary. Thanks....
